### ISSUE TITLE
Infinite loop with embedded comments in an instruction

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-language-service#69]
```Dockerfile
ENV \
# common variables:
  ENV1=something
  ENV2=999
```
```TypeScript
import { DockerfileLanguageServiceFactory } from 'dockerfile-language-service'
let content = "ENV \\\n# common variables:\n  ENV1=something \\\n  ENV2=999";
const service = DockerfileLanguageServiceFactory.createLanguageService();
service.computeSemanticTokens(content);
```
```
/dockerfile-language-service/out/src/dockerSemanticTokens.js:274
    createToken(instruction, range, tokenType, tokenModifiers = [], checkVariables = true, checkStrings = false, checkNewline = true) {
               ^

RangeError: Maximum call stack size exceeded
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:274:16)
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:451:18)
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:451:18)
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:451:18)
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:451:18)
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:451:18)
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:451:18)
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:451:18)
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:451:18)
    at DockerSemanticTokens.createToken (/dockerfile-language-service/out/src/dockerSemanticTokens.js:451:18)
```

**Comment by rcjsuen** [comment]
This is likely due to a bug in the parser. See https://github.com/rcjsuen/dockerfile-ast/issues/80.

**Comment by luismanuelmontoro** [comment]
I have the same problem, and I solved changing a character. Space " " has something strange.

**Comment by rcjsuen** [comment]
@luismanuelmontoro Maybe you encountered #74? Do you still have your original Dockerfile that you can share with me?

**Comment by luismanuelmontoro** [comment]
Not, sorry.
